export const initialFilters = {
    animalType: '',
    animalVariety: '',
    location: '',
    petOrigin: '',
    minPrice: '',
    maxPrice: '',
    free: false,
    minAnimalAge: '',
    maxAnimalAge: '',
    minAgeUnit: 'місяці (-ів)',
    maxAgeUnit: 'місяці (-ів)',
    gender: '',
    chip: false,
    sterilization: false,
    parasite: false,
    vaccination: false,
    passport: false,
    pedigree: false,
    metrics: false,
    cynology: false,
};
